### ISSUE TITLE
peerstore log for csv in hex?

### ISSUE THREAD

**Issue by jrhea** [protolambda/rumor#6]
when logging peerstore to a csv using the following command: `peer track tee --dest=csv --path=yermom.log` the values look like they are in hex (this doesn't seem to be the case for json).  See below:

```csv
op,time_ms,key,value
put,1597339765618,/peers/keys/AASQQAQSEEBFU64XBFNERFJXDYLEQ7FTQSQGBYSJ6RVQR4T4UOZOC74CKABKNFY/priv,0802122084721c74497548e3d5aeb12277a32e567e2da45bdc607c0d81ae9c93e7e26063
put,1597339765618,/peers/keys/AASQQAQSEEBFU64XBFNERFJXDYLEQ7FTQSQGBYSJ6RVQR4T4UOZOC74CKABKNFY/pub,08021221025a7b97095a4895371e16487cb384a060e249f46b08f27ca3b2e17f825002a697
put,1597339765650,/peers/addrs/AASQQAQSEEBDCWJUABVZR7IYNUP4YFQZKGKV5HSDKH374L3CUGI6GMTG4T6QEHQ,0a2700250802122102315934006b98fd186d1fcc161951955e9e4351f7fe2f62a191e33266e4fd021e12170a08043441a30806232810edf1d5f9051880e0ba84bf03
put,1597339765650,/peers/addrs/AASQQAQSEEBDCWJUABVZR7IYNUP4YFQZKGKV5HSDKH374L3CUGI6GMTG4T6QEHQ,0a2700250802122102315934006b98fd186d1fcc161951955e9e4351f7fe2f62a191e33266e4fd021e12170a08043441a30806232810edf1d5f9051880e0ba84bf03
put,1597339766216,/peers/keys/AASQQAQSEEBDCWJUABVZR7IYNUP4YFQZKGKV5HSDKH374L3CUGI6GMTG4T6QEHQ/pub,0802122102315934006b98fd186d1fcc161951955e9e4351f7fe2f62a191e33266e4fd021e
put,1597339766219,/peers/addrs/AASQQAQSEEBEBO74LPZ2JMM4IRRSDE3JVJNIARMGRP4ZRCS5GNLK3Q7SUSMOTPA,0a270025080212210240bbfc5bf3a4b19c4463219369aa5a8045868bf9988a5d3356adc3f2a498e9bc12170a080436902b2b06232810eef1d5f9051880e0ba84bf03
put,1597339766219,/peers/addrs/AASQQAQSEEBEBO74LPZ2JMM4IRRSDE3JVJNIARMGRP4ZRCS5GNLK3Q7SUSMOTPA,0a270025080212210240bbfc5bf3a4b19c4463219369aa5a8045868bf9988a5d3356adc3f2a498e9bc12170a080436902b2b06232810eef1d5f9051880e0ba84bf03
put,1597339766268,/peers/keys/AASQQAQSEEBEBO74LPZ2JMM4IRRSDE3JVJNIARMGRP4ZRCS5GNLK3Q7SUSMOTPA/pub,080212210240bbfc5bf3a4b19c4463219369aa5a8045868bf9988a5d3356adc3f2a498e9bc

```

**Comment by protolambda** [comment]
The CSV is more for debugging. I recommend the json format instead. The csv is raw Key-value, as represented in the datastore itself. The JSON is translated, with human readable data, and structure. One line per entry like CSV, but looking more like an event. Then just merge the data of those entries, to reconstruct the most recent keystore.

**Comment by protolambda** [comment]
There's now a new format, `evcsv`, which expands the json events into csv log entries.
Headers: `"op", "time_ms", "peer_id", "key", "value"`

The code (hack) to get the structure flattened into entries: https://github.com/protolambda/rumor/blob/8a0e731af0731d5955efcb4063d081369c2ce66a/p2p/track/dstee/translate/translate.go#L134

Note that regex match option still uses keys for the underlying datastore, so you can't directly filter all individual keys in this translated format. But after you've the detailed csv stream, you can filter it how you like it outside of rumor anyway.
